### ISSUE TITLE
[BUG] Animating the movement on large areas throws exceptions

### ISSUE THREAD

**Issue by tratteo** [JaffaKetchup/flutter_map_tile_caching#115]
## Animating the movement in the map on large areas
Using a cached tileProvider with behaviour `cacheFirst` and moving on the map (I am doing around 100 Km in 1 second) causes tons of this errors to be thrown: 

![image](https://user-images.githubusercontent.com/31132987/226171396-3ad4b501-0e77-479a-aaf2-fb2c862f3fdb.png)
<img width="520" alt="FMTCcrash2" src="https://user-images.githubusercontent.com/31132987/226171608-06253274-a82a-4654-8854-704b5d457905.png">
-----

### In this case I am offline and I try to move out of the cached zone

In this case I am offline and I am using the cached tile provider. Instead of being catched and logged, the error is thrown, causing tons of more exceptions per tile. I think this is related to the issue above.

![image](https://user-images.githubusercontent.com/31132987/226172109-438a3f2d-f7f8-4706-911b-986dc31b91b3.png)

### What is the expected behaviour?

Silently fail or at least prevent exceptions to be actually thrown. 
The error indeed does not happen when not using the cached tile provider.

### How can we reproduce this issue?

- Cache a zone
- Open a map using the cached tile provider
- Animate a movement (around 80Km/s)

### Do you have a potential solution?

The second error is thrown because of the first one, this is my guess. Indeed in case the first error is not thrown, the `FMTCBrowingError` is thrown silently (correctly)

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Often: Occurs more often than when it doesn't

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for known issues in the GitHub tracker and [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#known-issues)
- [X] I have completed the pre-report checks listed [on the docs site](https://fmtc.jaffaketchup.dev/known-issues-and-reporting#reporting-a-bug)
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment]
Hi @tratteo,

In regards to the second issue, there is nothing I can do to prevent it. There are no image bytes to return from the `ImageProvider` - so the only possible exit is through throwing an exception. Every `ImageProvider` will do this in the event that it can't retrieve an image.
Sometimes Flutter decides to report this silently, and sometimes it doesn't: but I always throw this in the same circumstances every time. You can check the code here: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/3d723ed052f0e27de50e2f3db351ad95e43c5516/lib/src/providers/image_provider.dart#L157-L173

In regards to the first issue, that code isn't part of my library, and looks to be part of Flutter's `ImageCache`. It actually looks as though this could be a bug in Flutter - it might be worthwhile opening an issue there and linking here.

Whilst they are likely related, Flutter shouldn't be throwing this kind of error. It likely occurs because Flutter thinks there is a cached image at that key, but in reality, there isn't.

Can you try the following solution when you get a moment? Fork this project and depend on it with an override, then replace the following lines:

https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/3d723ed052f0e27de50e2f3db351ad95e43c5516/lib/src/providers/image_provider.dart#L97-L102

with these:

```dart
final error = FMTCBrowsingError(throwError, throwErrorType!);
await evict();
// ImageCache().evict(key); // Uncomment this one if the issue isn't solved without it

provider.settings.errorHandler?.call(error);
throw error;
```

**Comment by JaffaKetchup** [comment]
flutter_map v4 may support disabling of loading and pruning of new tiles on demand, for example during animations. See the bottom of https://github.com/fleaflet/flutter_map/pull/1475#issue-1645808772 for more info.
