### ISSUE TITLE
[BUG] (V9) Missing tiles?

### ISSUE THREAD

**Issue by eidolonFIRE** [JaffaKetchup/flutter_map_tile_caching#149]
### What is the bug?

Scrubbing around the map with new V9, I'm occasionally getting a vomit of these messages. It seems it doesn't actually crash... but I have seen for some users this will strangely bog down their phone / freeze the app.

The tiles do eventually load half a second later, so I'm not confident I know what's happening... my suspicion is I'm getting rate limited by tile provider? Can I rate limit my client to test?

```
I/flutter ( 4918): #0      FMTCImageProvider._loadAsync.finishWithError (package:flutter_map_tile_caching/src/providers/image_provider.dart:70:7)
I/flutter ( 4918): <asynchronous suspension>
I/flutter ( 4918): #1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:985:3)
I/flutter ( 4918): <asynchronous suspension>
I/flutter ( 4918): 
I/flutter ( 4918): Store name: topo
I/flutter ( 4918): Tile coordinates: TileCoordinate(666, 1590, 12)
I/flutter ( 4918): Current provider: FMTCImageProvider()
I/flutter ( 4918): ═════════════════════════════════════════════════════════════════
I/flutter ( 4918):  : null

════════ Exception caught by image resource service ════════════════════════════
FMTCBrowsingError (FMTCBrowsingErrorType.negativeFetchResponse): Failed to load the tile from the cache or the network because it was missing from the cache and the server responded with a HTTP code other than 200 OK. Check that the `TileLayer.urlTemplate` is correct, that any necessary authorization data is correctly included, and that the server serves the viewed region.
════════════════════════════════════════════════════════════════════════════════
```

### How can we reproduce it?

-

### Platforms

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Hi @eidolonFIRE,

Thanks for trying v9 out! There's two things you can try:
 * Set an `errorHandler` in the `FMTCTileProviderSettings` to get the error and response, so you can check the status code yourself. It would be good if you could let me know what this is.
 * Set `fallbackToAlternativeStore` to `false` in `FMTCTileProviderSettings`. This is a new feature, relatively untested, and could be slowing the error handling right down, especially if you have a lot of tiles. Let me know how this goes.

There is no rate limiting functionality in the provider, because it is kind of assumed the tile server should be able to hold up to general browsing. Did this issue occur in previous versions, but didn't cause slow downs?

**Comment by JaffaKetchup** [comment]
Hey @eidolonFIRE,
Did you have time to try my suggestions above? No worries if not of course :)

**Comment by eidolonFIRE** [comment]
I think I found the issue actually... I was creating my tile providers in the widget tree and for whatever reason they were getting re-created very frequently. (half a dozen times each time you move around the map). I think it was generating massive spam.

Been swamped so I haven't gotten back to it in a while to fully verify, but lazy building the providers in static space so they are persistent seemed to solve the issue. It also fixed issues on < v9.

**Comment by JaffaKetchup** [comment]
Ah, that's a good catch! I'll add it to the docs. Let me know if there's anything else not working!

**Comment by JaffaKetchup** [comment]
Added a detailed guide for optimal implementation to the v10 docs: https://fmtc.jaffaketchup.dev/v10-beta/basic-usage/integrating-with-a-map.
