### ISSUE TITLE
Do not download tiles if are already saved

### ISSUE THREAD

**Issue by Filiponesco** [JaffaKetchup/flutter_map_tile_caching#23]
If we call downloadRegion it will download all tiles. Can we add extra functionality to download only not downloaded tiles?

**Describe the solution you'd like**
Get from database saved tiles, do not download this tiles

**Describe alternatives you've considered**
If we have hard coded region in app, we can check if amount of saved tiles is equal to tiles for specific region. When is equal do not download. Problem in this case is if some tiles are saved on database, because we start downloading all tiles again.

**Comment by JaffaKetchup** [comment]
Hi there,
I haven't previously implemented this checking because there was not enough gain in speed doing this compared to just redownloading the tile. Also, it allowed for tiles to be 'refreshed' and updated.
However, the new v4.0.0 update changes the backend storage system to use the filesystem instead of an SQL database, and therefore the check to see if a tile already exists would be quick, as the path to check for the existence of the tile can be constructed at download time now.
Therefore, as part of v4.0.0, I will add an option to `preventRedownloading`.

I will leave this issue open for now, until v4.0.0 is released, thanks for your interest.

If this library helps you, please leave a like on [pub.dev](https://pub.dev/packages/flutter_map_tile_caching) and a star on GitHub, and potentially consider donating: it really helps!

**Comment by JaffaKetchup** [comment]
Hi,
This is available as of v4.0.0-dev.3 and will be included in the final release of v4. Therefore, I will now close this issue as it is resolved and available.
Thanks for your support!

**Comment by Filiponesco** [comment]
1. Downloading map for works fully offline, but when user has access to internet showing map with more details.
2. Encyklopedia app for National Park.
3. Android and iOS.
4. 9/10. Hard: pick custom region. Not named constructors for lat, long. Missing downloaded PNG tiles. Not saw info in docs for limit in number of tiles to download from OSM API. I saw only hard coded info.
5. Add link to doc from OSM.

**Comment by JaffaKetchup** [comment]
Thanks for the valuable feedback! Hopefully v4 has made some of this easier, and v5 will make it even easier (hopefully!).
