### ISSUE TITLE
[QUESTION] How should the example-app update work?

### ISSUE THREAD

**Issue by eae1212** [JaffaKetchup/flutter_map_tile_caching#81]
### What is the bug?

I changed the version of the application to an older one, 
installed the application on the device (Samsung S21 , Android 13), 
saw the possibility of updating on the update page, 
the update was downloaded, then the application was unloaded, and that's it.

What should happen next?

### What is the expected behaviour?

updater starts

### How can we reproduce this issue?

```dart
change the app version to an older one and try to update app
```

### Do you have a potential solution?

no

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @eae1212,
Currently the updater is buggy on Android, not sure why, and I don't think there's a lot I can do about it. It's completley seperate to the functioning of this library (just a nice-to-have kind of thing), so I'm going to close this.
Easiest thing to do is just install newer update packages manually. Note that it does work on Windows.
Thanks for the report!

**Comment by eae1212** [comment]
Hi @JaffaKetchup , 
thanks for your help! 
where can I find the downloaded update in android?

**Comment by JaffaKetchup** [comment]
No problem!

The APK at [prebuiltExampleApplications/AndroidApplication.apk](https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/main/prebuiltExampleApplications/AndroidApplication.apk) is always kept up to date by an Action. To update the app already on your device, you can just install this (it should update instead of uninstall & reinstall).
In fact the internal update logic just uses this APK. It doesn't work properly because it doesnt get time to execute the new downloaded APK before the currently-running app is removed. Maybe I'll fix this in [v7](https://github.com/JaffaKetchup/flutter_map_tile_caching/tree/next-version).
